apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: kinesis-event-source
spec:
  subject:
    apiVersion:
    kind: Service
    name: kinesis-knative-eventer
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: video-sink